import AppProvider from '@/context/app.context'
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import GameProvider from '@/context/socket.context'
import SocketProvider from '@/context/game.context'
import ChatProvider from '@/context/chat.context'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ft_transcendence',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AppProvider>
        <SocketProvider>
          <ChatProvider>
          <GameProvider>
            <body className={montserrat.className}>{children}</body>
          </GameProvider>
          </ChatProvider>
        </SocketProvider>
      </AppProvider>
    </html>
  )
}
