import AppProvider from '@/context/app.context'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GameProvider from '@/context/socket.context'
import SocketProvider from '@/context/game.context'
import ChatProvider from '@/context/chat.context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ft_transcendence',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AppProvider>
        <GameProvider>
          <SocketProvider>
            <ChatProvider>
              <body className={inter.className}>{children}</body>
            </ChatProvider>
          </SocketProvider>
        </GameProvider>
      </AppProvider>
    </html>
  )
}
